feat: "initial commit"
LacticWhale/socks5 pull request #2
Opened 2022-06-07 01:40 UTC by LacticWhale

Initial commit. Code examples are included.

Known issues: None.

2022-06-07 21:18 UTC, Zekfad requested changes
some changes required

2022-06-07 21:18 UTC, Zekfad commented on lib/src/state.dart
> +  handshake,
use ing

2022-06-07 21:18 UTC, Zekfad commented on lib/src/state.dart
> +  authentication,
use ing

2022-06-07 21:18 UTC, Zekfad commented on lib/src/state.dart
> +  // binded, // To hard to understand
because it's "bound"

2022-06-07 21:18 UTC, Zekfad commented on lib/src/state.dart
> +  // binded, // To hard to understand
and maybe better to use "listening"?

2022-06-07 21:18 UTC, Zekfad commented on lib/src/tcp_connection.dart
> +    clientPort = _connection.socket.remotePort;
use initialization

2022-06-07 21:18 UTC, Zekfad commented on lib/src/tcp_connection.dart
> +  TcpConnection.extend(this._connection) {
better to say "from"

2022-06-07 21:18 UTC, Zekfad commented on lib/src/tcp_connection.dart
> +      ]));
format code

2022-06-07 21:18 UTC, Zekfad commented on lib/src/tcp_connection.dart
> +      _connection.getAddressTypeAsBite(targerAddress.type),
bite?

2022-06-07 21:18 UTC, Zekfad commented on lib/src/tcp_connection.dart
> +      _connection.getAddressTypeAsBite(targerAddress.type),
and just name it getAddressType, and isn't it must be a private method?

2022-06-07 21:18 UTC, Zekfad commented on lib/src/tcp_connection.dart
> +      outcomingSink.add(data);
name it clientSink

2022-06-07 21:18 UTC, Zekfad commented on lib/src/tcp_connection.dart
> +    final target = await Socket.connect(targerAddress, targerPort);
typo targer

2022-06-07 21:18 UTC, Zekfad commented on lib/src/typed_connections.dart
> +}
accept must have the same signature for both (with `{bool connect}`)

2022-06-07 21:18 UTC, Zekfad commented on lib/src/udp_connection.dart
> +          _connection, 'Connection doesn\'t have associated upd socket');
UDP must be capitalized

2022-06-07 21:18 UTC, Zekfad commented on lib/src/state.dart
> +}
add docs

2022-06-07 21:18 UTC, Zekfad commented on lib/src/udp_connection.dart
> +      ]));
format

2022-06-07 21:18 UTC, Zekfad commented on lib/src/udp_connection.dart
> +        Datagram? dg = _targetSocket.receive();
bad name

2022-06-07 21:18 UTC, Zekfad commented on lib/src/udp_connection.dart
> +  final _incomingClientStreamController = StreamController<UDPPacket>();
name it `_clientPackets`

2022-06-07 21:18 UTC, Zekfad commented on lib/src/udp_packet.dart
> +    }[_type]!;
this map is const

2022-06-07 21:18 UTC, Zekfad commented on pubspec.yaml
> +description: A starting point for Dart libraries or applications.
add description

2022-06-07 21:36 UTC, LacticWhale commented on examples/1_simple_proxy.dart
> +      await connection.forward();
yeah

2022-06-07 22:27 UTC, LacticWhale commented on lib/src/connection.dart
> +  }
👍

2022-06-07 23:02 UTC, LacticWhale commented on lib/src/connection.dart
> +      reject(message: Uint8List.fromList([1, 1]));
no

2022-06-08 01:02 UTC, Zekfad requested changes

2022-06-08 22:11 UTC, Zekfad requested changes
also add comments with short explanation of example before main function

2022-06-08 22:11 UTC, Zekfad commented on lib/src/server.dart
> +  }
extract to file

2022-06-08 22:11 UTC, Zekfad commented on lib/src/tcp/tcp_connection.dart
> +  final _outcomingStreamController = StreamController<Uint8List>();
outgoing

2022-06-08 22:11 UTC, Zekfad commented on lib/src/tcp/tcp_connection.dart
> +      ]
why?

2022-06-08 22:11 UTC, Zekfad commented on lib/src/udp/udp_connection.dart
> +        ),
just use `_connection.associatedAddress != null && _connection.associatedPort != null`

2022-06-08 22:11 UTC, Zekfad commented on lib/src/udp/udp_connection.dart
> +      ...[(port! & 0xff00) >> 8, port! & 0x00ff],
why?

2022-06-08 22:11 UTC, Zekfad commented on lib/src/udp/udp_connection.dart
> +    if (port == null) {
what is that port?

2022-06-08 22:11 UTC, Zekfad commented on lib/src/udp/udp_connection.dart
> +    accept(true);
no await?
also what if bind failed?

2022-06-08 22:11 UTC, Zekfad commented on lib/src/internet_address_type_extention.dart
> +InternetAddressType internetAddressTypeFrom(int byte) {
shouldn't it be in SocksUdpPacket?

2022-06-08 22:11 UTC, Zekfad commented on lib/src/udp/udp_connection.dart
> +      final packet = SocksUdpPacket.tryParse(datagram);
tryParse means nullable, parse is tryParse call with throw state error on null value

2022-06-08 22:11 UTC, Zekfad commented on lib/src/udp/udp_server.dart
> +  final Future<RawDatagramSocket> _socketFuture;
bad name

2022-06-08 22:11 UTC, Zekfad commented on lib/src/udp/udp_server.dart
> +        print(event);
?

2022-06-08 22:11 UTC, Zekfad commented on lib/src/udp/udp_server.dart
> +      throw SocketException('Server haven\'t yet been opened.');
bad wording

2022-06-08 22:28 UTC, LacticWhale commented on examples/3_tcp_filtering_proxy.dart
> +  if (mask.length < 4) throw RangeError('Mask size must be 4');
i forgor

2022-06-08 22:29 UTC, LacticWhale commented on examples/4_tcp_spoofing.dart
> +      if (connection.targetAddress != InternetAddress('93.184.216.34')) {
example.com, cause unix addresses works only on linux, mac

2022-06-08 22:29 UTC, LacticWhale commented on examples/5_udp_spoofing.dart
> +        // reject datagrams from unknown clients
👍

2022-06-08 22:39 UTC, LacticWhale commented on examples/6.1_udp_reading.dart
> +          ),
datagram.data = socks5header aka frame + data

2022-06-08 22:40 UTC, LacticWhale commented on lib/src/enums/authentication_method.dart
> +  // /// 0x01 GSSAPI
I messed up with values

2022-06-08 22:48 UTC, LacticWhale commented on lib/src/tcp/tcp_connection.dart
> +      ]
?

2022-06-08 22:51 UTC, LacticWhale commented on lib/src/udp/udp_connection.dart
> +      ...[(port! & 0xff00) >> 8, port! & 0x00ff],
?

2022-06-08 22:59 UTC, LacticWhale commented on lib/src/udp/udp_connection.dart
> +      final packet = SocksUdpPacket.tryParse(datagram);
noted

2022-06-08 23:01 UTC, LacticWhale commented on lib/src/udp/udp_server.dart
> +        print(event);
this way _socket isn't future

2022-06-08 23:04 UTC, Zekfad commented on examples/4_tcp_spoofing.dart
> +      if (connection.targetAddress != InternetAddress('93.184.216.34')) {
unix address is actually a file fyi...

2022-06-08 23:06 UTC, Zekfad commented on lib/src/udp/udp_server.dart
> +        print(event);
that's bad naming over there then

2022-06-14 21:49 UTC, closed without merging